# Rainfall Weather Forcasting

In [1]:
import numpy as np
import pandas as pd


In [6]:
dataset=pd.read_csv(r'C:\Users\Chinmay\Downloads\weatherAUS.csv')
X=dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y=dataset.iloc[:,-1].values

In [7]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [8]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [9]:
Y=Y.reshape(-1,1)

In [10]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


In [11]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)

In [12]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,0]=le1.fit_transform(X[:,0])
le2=LabelEncoder()
X[:,4]=le2.fit_transform(X[:,4])
le3=LabelEncoder()
X[:,6]=le3.fit_transform(X[:,6])
le4=LabelEncoder()
X[:,7]=le4.fit_transform(X[:,7])
le5=LabelEncoder()
X[:,-1]=le5.fit_transform(X[:,-1])
le6=LabelEncoder()
Y=le6.fit_transform(Y)

C:\Users\Chinmay\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
print(X)

[[1 13.4 22.9 ... 16.9 21.8 0]
 [1 7.4 25.1 ... 17.2 24.3 0]
 [1 12.9 25.7 ... 21.0 23.2 0]
 ...
 [9 5.4 26.9 ... 12.5 26.1 0]
 [9 7.8 27.0 ... 15.1 26.0 0]
 [9 14.9 19.0 ... 15.0 20.9 0]]


In [14]:
print(Y)

[0 0 0 ... 0 0 0]


In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [16]:
print(X)

[[-1.51577598  0.04039106 -0.15101108 ... -0.15006358 -0.10175254
  -0.55609919]
 [-1.51577598 -1.07478085  0.20800875 ... -0.09661746  0.318031
  -0.55609919]
 [-1.51577598 -0.05253993  0.30592325 ...  0.58036664  0.13332624
  -0.55609919]
 ...
 [ 1.01389522 -1.44650482  0.50175225 ... -0.93393991  0.62027515
  -0.55609919]
 [ 1.01389522 -1.00043606  0.51807133 ... -0.47074026  0.60348381
  -0.55609919]
 [ 1.01389522  0.31918404 -0.78745533 ... -0.48855563 -0.25287462
  -0.55609919]]


In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=0)

In [18]:
print(X_train)

[[ 0.06526852  0.8024252  -0.18364925 ...  0.40221293 -0.15212657
  -0.55609919]
 [ 1.64631302  0.46787363 -0.37947825 ...  0.06372088 -0.4879534
  -0.55609919]
 [-1.51577598 -1.33498763 -0.15101108 ... -0.86267843  0.03257819
  -0.55609919]
 ...
 [-0.25094038 -0.75881547 -0.90168891 ... -0.70234009 -0.87415426
  -0.55609919]
 [ 1.33010412  1.08121818  0.28960417 ...  0.93667407  0.28444832
   1.79824035]
 [ 0.38147742 -0.4800225  -1.50549499 ... -0.7557862  -1.34431183
   1.79824035]]


In [19]:
print(Y_train)

[0 0 0 ... 1 0 1]


In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=0)

In [21]:
classifier.score(X_train,Y_train)

0.9998516320474777

In [24]:
Y_pred=classifier.predict(X_test)

In [25]:
print(Y_pred)

[0 0 0 ... 1 0 0]


In [26]:
Y_pred=le6.inverse_transform(Y_pred)

In [27]:
print(Y_pred)

['No' 'No' 'No' ... 'Yes' 'No' 'No']


In [28]:
print(Y_test)

[1 0 0 ... 1 0 0]


In [29]:
Y_test=Y_test.reshape(-1,1)
Y_pred=Y_pred.reshape(-1,1)

In [32]:
df=np.concatenate((Y_test,Y_pred), axis=1)
dataframe=pd.DataFrame(df,columns=['Rain on Tomorrow','Prediction of Rain'])

In [33]:
print(dataframe)

     Rain on Tomorrow Prediction of Rain
0                   1                 No
1                   0                 No
2                   0                 No
3                   0                 No
4                   1                Yes
...               ...                ...
1680                1                 No
1681                0                 No
1682                1                Yes
1683                0                 No
1684                0                 No

[1685 rows x 2 columns]
